### #* Listar cuentas
GET http://localhost:3000/api/accounts?page=1&limit=5
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZW1haWwiOiJqb2huZG9lQGdtYWlsLmNvbSIsImlzX2FkbWluIjpmYWxzZSwic3RhdHVzIjp0cnVlLCJpYXQiOjE3MzQ3NDgxMjAsImV4cCI6MTczNDc1NTMyMH0.nzsbEn4uUGVQmMINTUGbEu65RF4kwMp_StuSL6p_h2U

{}

### #* Listar cuentas
GET http://localhost:3000/api/accounts?page=1&limit=10&search=john
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZW1haWwiOiJqb2huZG9lQGdtYWlsLmNvbSIsImlzX2FkbWluIjpmYWxzZSwic3RhdHVzIjp0cnVlLCJpYXQiOjE3MzQzMTk0NDksImV4cCI6MTczNDMyNjY0OX0.L46eOdLbJFvYY1Q4D9WVugHN5HwXjTRr0dGfAq_GhuY

{}

### #* Crear cuenta
POST http://localhost:3000/api/accounts/new
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZW1haWwiOiJqb2huZG9lQGdtYWlsLmNvbSIsImlzX2FkbWluIjpmYWxzZSwic3RhdHVzIjp0cnVlLCJpYXQiOjE3MzQ4MjUxMDgsImV4cCI6MTczNDgzMjMwOH0.5eDPWpSJYH4swO8w-9ZdcEZYDyx1VzpXLiML_ggvMVs

{
    "account_email":"jorge@gmail.com"
}

### #* edit cuenta
PUT http://localhost:3000/api/accounts/edit/1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZW1haWwiOiJqb2huZG9lQGdtYWlsLmNvbSIsImlzX2FkbWluIjpmYWxzZSwic3RhdHVzIjp0cnVlLCJpYXQiOjE3MzQ5MTg4MTgsImV4cCI6MTczNDkyNjAxOH0.lEyzHIq8MtnLXLwXujPrx1xSVZUbTB1loOMHBq6Og9U

{
    "account_email":"johndoe@gmail.com",
    "status": true
}

### #* deleted account
DELETE  http://localhost:3000/api/accounts/8
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZW1haWwiOiJqb2huZG9lQGdtYWlsLmNvbSIsImlzX2FkbWluIjpmYWxzZSwic3RhdHVzIjp0cnVlLCJpYXQiOjE3MzM2MjczOTMsImV4cCI6MTczMzYzNDU5M30.WhXh9-_RLyaWowhTvx93QeeaGZkMoAfby4S4FWzhKQI

{}