@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZW1haWwiOiJqb2huZG9lQGdtYWlsLmNvbSIsImlzX2FkbWluIjpmYWxzZSwic3RhdHVzIjp0cnVlLCJkZXJpdmVkS2V5Ijp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjpbNDksMTMwLDIwMSw2NSw1NCwyMjUsMTI3LDIyOCwzLDI1NSwxNDIsODUsMTUwLDIxNywyNDAsMTk2LDg2LDE2NSwzMSw3NSw5NywxMjksMTIwLDEyOCwxODUsMTU3LDgwLDY4LDExNiwyOCw3NSwxMzldfSwiaWF0IjoxNzM1OTYyNDI5LCJleHAiOjE3MzU5Njk2Mjl9.rp1GdEcDZGk3kNg3hKefWgonSfc2RsKfv1yA94d8Ozg


###* Crear los metodos de recuperación basado en los detalles de la subscripción
POST http://localhost:3000/api/subcriptions-details/41/methods-recovery/new
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "method_type":"email_recovery",
  "method_value":"pepito019@gmail.com"
}