// Generated by https://quicktype.io

import { vashApi } from "@/api/vashApi";
import {
  AuthCheckStatusRespone,
  AuthResponse,
} from "@/infrastructure/interfaces/auth.responses";
import { User } from "../../../domain/entities/user";

import { ErrorMapper } from "@/infrastructure/mapper/error.mapper";

export class AuthService {
  static login = async (user_name: string, password: string) => {
    try {
      const { data } = await vashApi.post<AuthResponse>("/auth/sign-in", {
        user_name,
        password,
      });
      return data;
    } catch (error) {
      //TODO REfactor error response
      console.log(error);
      const response_error = ErrorMapper.handleError(
        error,
        "Ops , you can't logIn"
      );

      console.log(response_error);
      throw response_error;
    }
  };

  static checkStatusAuth = async () => {
    try {
      const { data } = await vashApi.get<AuthCheckStatusRespone>("/auth/renew");

      return data;
    } catch (error) {
      const response_error = ErrorMapper.handleError(
        error,
        "Ops , you can't register User"
      );

      throw response_error;
    }
  };

  static registerUser = async (payload: User) => {
    try {
      const { data } = await vashApi.post<AuthResponse>("/auth/sign-up", {
        ...payload,
      });
      return data;
    } catch (error) {
      console.log(error);
      const response_error = ErrorMapper.handleError(
        error,
        "Ops , you can't register User"
      );
      console.log(response_error);
      throw response_error;
    }
  };

  static logout = async () => {
    try {
      const { data } = await vashApi.post<{ ok: boolean; message: string }>(
        "/auth/logout"
      );
      return data;
    } catch (error) {
      console.log(error);
      const response_error = ErrorMapper.handleError(
        error,
        "Ops , you can't logout"
      );
      console.log(response_error);
      throw response_error;
    }
  };
}
