// Generated by https://quicktype.io

import { AxiosError } from "axios";
import { vashApi } from "@/api/vashApi";
import { AuthResponse } from "@/infrastructure/interfaces/auth.responses";

export class AuthService {
  static login = async (user_name: string, password: string) => {
    try {
      const { data } = await vashApi.post<AuthResponse>("/auth/sign-in", {
        user_name,
        password,
      });

      return data;
    } catch (error) {
      if (error instanceof AxiosError) {
        console.log(error.response?.data);
        throw new Error(JSON.stringify(error.response?.data));
      }
      // console.log(error);
      throw new Error("Unable to login");
    }
  };

  static checkStatusAuth = async () => {
    try {
      const { data } = await vashApi.get<AuthResponse>("/auth/renew");

      return data;
    } catch (error) {
      if (error instanceof AxiosError) {
        console.log(error.response?.data);
        throw new Error(error.response?.data.message);
      }
      throw new Error("UnAuthorizard");
    }
  };
}
