

###* auth module

###
POST http://localhost:3000/api/auth/sign-in
Content-Type: application/json

{
 
    "password":"123456",
    "user_name":"jsalgado@gmail.com"
}

###
GET http://localhost:3000/api/auth/renew
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTksImVtYWlsIjoianNhbGdhZG9lY2hlQGdtYWlsLmNvbSIsImlzX2FkbWluIjpmYWxzZSwic3RhdHVzIjp0cnVlLCJpYXQiOjE3Mjg0NDcwMDUsImV4cCI6MTcyODQ1NDIwNX0.jGlJN6gJISgKC8dgZqzEmMBQ9RPhqzgVcCEvtFwH1wU

{
 
    "password":"123456",
    "user_name":"jsalgadoeche@gmail.com"
}

###*users module

POST http://localhost:3000/api/users/new
Content-Type: application/json

{
    "email":"jsalgadoecheverria19@gmail.com",
    "password":"123456",
    "user_name":"jorge0191"
}
###
GET http://localhost:3000/api/users
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTUsImVtYWlsIjoianNhbGdhZG9AZ21haWwuY29tIiwiaXNfYWRtaW4iOnRydWUsInN0YXR1cyI6dHJ1ZSwiaWF0IjoxNzI4NjA3MzUxLCJleHAiOjE3Mjg2MTQ1NTF9.heC4YScfKxd4ZoDcMROv6QQgbBW9t_srg9Zf6ko95tU

{
   
}

###
POST http://localhost:3000/api/auth/sign-up
Content-Type: application/json

{
    "email":"jsalgadoeche@gmail.com",
    "password":"123456",
    "user_name":"jorge99"
}

###* module services
GET http://localhost:3000/api/services
Content-Type: application/json
