POST http://localhost:3000/api/users/new
Content-Type: application/json

{
    "email":"jsalgadoecheverria19@gmail.com",
    "password":"123456",
    "user_name":"jorge0191"
}
###
GET http://localhost:3000/api/users
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTksImVtYWlsIjoianNhbGdhZG9lY2hlQGdtYWlsLmNvbSIsImlzX2FkbWluIjpmYWxzZSwic3RhdHVzIjp0cnVlLCJpYXQiOjE3Mjg0NDI1NDgsImV4cCI6MTcyODQ0OTc0OH0.maA2tdetSj-9oU6oXParFAd2y3zVursPkHLeX4O0i7w

{
   
}

###
POST http://localhost:3000/api/auth/sign-up
Content-Type: application/json

{
    "email":"jsalgadoeche@gmail.com",
    "password":"123456",
    "user_name":"jorge99"
}

###
POST http://localhost:3000/api/auth/sign-in
Content-Type: application/json

{
 
    "password":"123456",
    "user_name":"jsalgadoeche@gmail.com"
}

###
GET http://localhost:3000/api/auth/renew
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTksImVtYWlsIjoianNhbGdhZG9lY2hlQGdtYWlsLmNvbSIsImlzX2FkbWluIjpmYWxzZSwic3RhdHVzIjp0cnVlLCJpYXQiOjE3Mjg0NDcwMDUsImV4cCI6MTcyODQ1NDIwNX0.jGlJN6gJISgKC8dgZqzEmMBQ9RPhqzgVcCEvtFwH1wU

{
 
    "password":"123456",
    "user_name":"jsalgadoeche@gmail.com"
}