name: Deploy React App to Render

on:
  push:
    branches:
      - develop
    paths:
      - 'client/**'  # Solo se activará cuando haya cambios en la carpeta 'client'

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      # Paso 1: Hacer checkout del código
      - name: Checkout code
        uses: actions/checkout@v2

      # Paso 2: Configurar Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'  # Cambia la versión según tus necesidades

      # Paso 3: Instalar dependencias
      - name: Install dependencies
        run: |
          cd client  # Navegar a la carpeta 'client'
          npm install

      # Paso 4: Construir la aplicación
      - name: Build the app
        run: |
          cd client 
          npm run build

      # Paso 5: Deply render
      - name: Deploy to Render
        uses: JorgeLNJunior/render-deploy@v1.4.4
        with:
          service_id: ${{ secrets.RENDER_SERVICE_ID }}
          api_key: ${{ secrets.RENDER_API_KEY }}
